version: '2'

services:
  app:
    image: 'fbc-bot'
    build:
      context: .
    container_name: fbc-bot-container
    ports: [ "8080:8080" ]
    environment:
      - DATABASE_URL=jdbc:postgresql://fbc-postgres-container/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=docker
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: fbc-postgres-container
    ports: [ "5432:5432" ]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker