version: '2'

services:
#  app:
#    image: 'fbc-bot'
#    build:
#      context: .
#    container_name: fbc-bot-container
#    ports: [ "8080:8080" ]
#    environment:
#      - DATABASE_URL=$DATABASE_URL
#      - DATABASE_USERNAME=$DATABASE_USERNAME
#      - DATABASE_PASSWORD=$DATABASE_PASSWORD
#    depends_on:
#      - db
  db:
    image: 'postgres'
    container_name: fbc-postgres-container
    ports: [ "5433:5432" ]
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD