spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:docker}
    hikari:
      schema: fbc-bot
      maximum-pool-size: 3
      idle-timeout: 10000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        order_inserts: true
        order_updates: true
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          fetch_size: 5000
    open-in-view: false

    show-sql: true

  flyway:
    schemas: fbc-bot

telegram:
  bot:
    botToken: ${TELEGRAM_BOT_TOKEN:6051083691:AAGV8y6IWaYIiAnCv7qS7vjsA88dUomr9lY}
    auditChatId: ${TELEGRAM_AUDIT_CHAT_ID:424189266}
    mainChatId: ${TELEGRAM_MAIN_CHAT_ID:-970277358}
    inlinePhotoUrl: https://i.ibb.co/Zz71HFH/FBC-logo-transparent.png
#    1768160429