spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fbc-bot}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:docker}
    hikari:
      maximum-pool-size: 3
      idle-timeout: 10000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        order_inserts: true
        order_updates: true
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          fetch_size: 5000
    open-in-view: false

telegram:
  bot:
    botToken: ${TELEGRAM_BOT_TOKEN}
    auditChatId: ${TELEGRAM_AUDIT_CHAT_ID}
    mainChatId: ${TELEGRAM_MAIN_CHAT_ID}
    inlinePhotoUrl: ${TELEGRAM_INLINE_PHOTO_URL}