spring:
  datasource:
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}
    hikari:
      schema: fbc-bot
      maximum-pool-size: 3
      idle-timeout: 10000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        order_inserts: true
        order_updates: true
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          fetch_size: 5000
    open-in-view: false

    show-sql: true

  flyway:
    schemas: fbc-bot

server:
  port: 5000

# Spring boot Actuator
management:
  server:
    address: 127.0.0.1
    port: 8081