spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:docker}
    hikari:
      schema: fbc-bot
      maximum-pool-size: 3
      idle-timeout: 10000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        order_inserts: true
        order_updates: true
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          fetch_size: 5000
    open-in-view: false

    show-sql: true

  flyway:
    schemas: fbc-bot

telegram:
  bot:
    botToken: ${TELEGRAM_BOT_TOKEN:6008183446:AAGQlTK3_-DBlO-dlZjyTND1FgVsTdkUjw4}
    auditChatId: ${TELEGRAM_AUDIT_CHAT_ID:360617541}
    mainChatId: -970277358

bereal:
  enabled: true